name: CI

description: Shared action with basic setup for each job

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        run_install: false

    - name: Setup Node (uses version in .nvmrc)
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Building packages
      run: pnpm build
      shell: bash
