name: Main workflow

# The event triggers are configured as following:
# - on branch main, trigger the workflow on every push
# - on any pull request, trigger the workflow
# This is to avoid running the workflow twice on pull requests.
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing dependencies and building packages
        uses: ./.github/actions/ci

      - name: Running static type checking
        run: pnpm typecheck

      - name: Running linters and tests
        run: pnpm jest --projects jest.{eslint,test,ts-test,bundle}.config.js --reporters github-actions
        env:
          CI: true

      - name: Building Visual Regression Tests application for UI components
        run: pnpm visual-testing-app:build

      - name: Running Visual Regression Tests for UI components
        run: pnpm vrt:components
        timeout-minutes: 20
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Checking bundle size of visual testing app
        run: pnpm bundlesize
        # env:
        # NOTE: it seems that currently bundlesize server is having problems
        # resulting in status code 500. Because of that, the bundlesize script
        # is not able to handle the response, resulting in the exit code command
        # to be 0, which makes the test pass.
        # To keep the bundlesize check, we avoid passing the token to the command.
        # This results in the script to run and fail in case of error, but no status
        # code is reported to the github PR.
        #   BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
