name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Pass a personal access token (using our `ct-release-bot` account) to be able to trigger
          # other workflows
          # https://help.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
          # https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148/8
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Installing dependencies and building packages
        uses: ./.github/actions/ci

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=npmjs@commercetools.com
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Building package READMEs
        run: pnpm generate-readmes
        env:
          CI: true

      - name: Storing release version for changeset
        id: release_version
        run: echo "VALUE=$(./scripts/print_release_version.sh)" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: dotansimha/changesets-action@v1.5.2
        with:
          commit: 'ci(changesets): version packages'
          publish: pnpm changeset publish
          version: pnpm changeset:version-and-format
          createGithubReleases: aggregate
          githubReleaseName: v${{ steps.release_version.outputs.VALUE }}
          githubTagName: v${{ steps.release_version.outputs.VALUE }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          SKIP_POSTINSTALL_DEV_SETUP: true

      # Publish canary releases only if the packages weren't published already
      - name: Publishing canary releases to npm registry
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          pnpm changeset version --snapshot canary
          pnpm changeset publish --tag canary
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
